// This file is auto-generated by AudioManager, please DO NOT change it manually
public enum Sounds
{
	GardensVillage,
	Track1,
	Track2,
}

public static class AudioManagerSoundsExtensions
{
	public static void Play(this AudioManager audio, Sounds sound) => audio.Play((int)sound);
}
